### ISSUE TITLE
Error with nuc_data_make with Python 3.6

### ISSUE THREAD

**Issue by reflynn** [pyne/pyne#982] opened 2018-01-26 19:47 UTC
nuc_data_make does not finish:

`Traceback (most recent call last):
  File "scripts/nuc_data_make", line 6, in <module>
    main()
  File "/home/reflynn/.local/lib/python3.6/site-packages/pyne/dbgen/nuc_data_make.py", line 155, in main
    make_map[mo](args)
  File "/home/reflynn/.local/lib/python3.6/site-packages/pyne/dbgen/atomic_mass.py", line 144, in make_atomic_mass
    with tb.openFile(nuc_data, 'r') as f:
AttributeError: module 'tables' has no attribute 'openFile'`

**Comment by scopatz** [comment] 2018-02-22 22:14
Thanks for reporting @reflynn.  Are you on the latest version of PyNE?  In the current version there are no references to `openFile` anywhere, which was the old API for pytables.

**Comment by reflynn** [comment] 2018-02-23 04:16
I reinstalled PyNE and got a different error this time:

```
Traceback (most recent call last):
  File "scripts/nuc_data_make", line 4, in <module>
    from pyne.dbgen.nuc_data_make import main
  File "/home/reflynn/.local/lib/python3.6/site-packages/pyne/dbgen/nuc_data_make.py", line 5, in <module>
    from pyne.utils import QAWarning
  File "/home/reflynn/.local/lib/python3.6/site-packages/pyne/utils.py", line 6, in <module>
    from pyne._utils import fromstring_split, fromstring_token, endftod,\
ImportError: cannot import name 'use_fast_endftod'
```

**Comment by scopatz** [comment] 2018-02-23 18:32
hmm that function defintiely works.  Can you provide more detail please?  How you installed PyNE, what directory you are running from, etc? Thanks

**Comment by opotowsky** [comment] 2020-08-12 14:17
I cannot reproduce this error. Given that initially it was an old version of PyNE, and the next error could be from an "unclean" reinstall (there's just not enough information), I propose we close this issue.

**Comment by opotowsky** [comment] 2020-08-12 14:19
@reflynn If you are still having this problem, feel free to reopen the issue and provide more context for the error. Thanks!

**Closed as completed by opotowsky** 2020-08-12 14:19 UTC
Labels: bug, build
