### ISSUE TITLE
Fe52 --> Mn52 --> Cr52 decay chain

### ISSUE THREAD

**Issue by ivoseitenzahl** [pyne/pyne#738] opened 2015-06-22 14:14 UTC
I noticed an issue in pyne material with the decay of Fe52. When Fe52 decays to Mn52 it ends up in a metastable state with half-life ~21.1 min. The half-life used for the chain in pyne materials appears to be that of the ground state of Mn52, which is ~5.591 days. The results is that, starting with a certain amount of Fe52, after several days a lot of material is still in the form of Mn52, although in reality most of it should be Cr52 already.

**Comment by scopatz** [comment] 2015-06-23 17:16
Is this a duplicate of #739?

**Comment by ivoseitenzahl** [comment] 2015-06-24 08:33
Sorry about the duplicate. I had very unstable wireless at a conference 
and it seemed as if my comment didn't post at first. I will send you a 
script that demonstrates the issue soon.

Cheers,
Ivo

**Comment by gonuke** [comment] 2020-08-10 23:42
Closed as duplicate of #739

**Closed as completed by gonuke** 2020-08-10 23:42 UTC
