### ISSUE TITLE
PyNE CPP no longer compiles with Clang

### ISSUE THREAD

**Issue by makeclean** [pyne/pyne#919] opened 2017-10-04 18:05 UTC
On my Mac the CPP part of PyNE no longer compiles, entirely due to cram.c, the error is

```In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:387:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstddef:44:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__nullptr:35:5: error: templates must
      have C++ linkage
    template <class _Tp>
    ^~~~~~~~~~~~~~~~~~~~```

Of course one can use brew to use and install gcc, just an FYI

**Comment by scopatz** [comment] 2017-10-05 19:24
Hi @makeclean - did you do a fully clean build (ie remove the build dir) when you switched compilers?  That is what I suspect this error is from, since the error is coming from deep within system headers.  Note that cram.hpp does not contain any templated code.

**Comment by scopatz** [comment] 2017-10-05 19:24
Thanks for reporting!

**Comment by makeclean** [comment] 2017-10-05 20:33
Yes, from a clean build, here is the full trace

```[  0%] Built target ReplicatePythonSourceTree
[  4%] Building CXX object src/CMakeFiles/pyne.dir/data.cpp.o
[  4%] Building CXX object src/CMakeFiles/pyne.dir/atomic_data.cpp.o
[  4%] Building C object src/CMakeFiles/pyne.dir/cram.c.o
[  5%] Building CXX object src/CMakeFiles/pyne.dir/enrichment.cpp.o
[  6%] Building CXX object src/CMakeFiles/pyne.dir/decay.cpp.o
[  8%] Building CXX object src/CMakeFiles/pyne.dir/enrichment_cascade.cpp.o
[  9%] Building CXX object src/CMakeFiles/pyne.dir/enrichment_symbolic.cpp.o
[ 10%] Building CXX object src/CMakeFiles/pyne.dir/jsoncpp.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pyne.dir/jsoncustomwriter.cpp.o
[ 13%] Building CXX object src/CMakeFiles/pyne.dir/material.cpp.o
[ 14%] Building CXX object src/CMakeFiles/pyne.dir/nucname.cpp.o
[ 16%] Building CXX object src/CMakeFiles/pyne.dir/particle.cpp.o
/Users/davisa/opt/pyne/src/particle.cpp:251:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
[ 17%] Building CXX object src/CMakeFiles/pyne.dir/rxname.cpp.o
1 warning generated.
[ 18%] Building CXX object src/CMakeFiles/pyne.dir/tally.cpp.o
[ 20%] Building CXX object src/CMakeFiles/pyne.dir/transmuters.cpp.o
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:387:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstddef:44:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__nullptr:35:5: error: templates must have C++
      linkage
    template <class _Tp>
    ^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:387:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstddef:44:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__nullptr:39:5: error: templates must have C++
      linkage
    template <class _Tp, class _Up>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:395:1: error: templates must have C++
      linkage
template <class _T1, class _T2> struct _LIBCPP_TEMPLATE_VIS pair;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:396:1: error: templates must have C++
      linkage
template <class _Tp> class _LIBCPP_TEMPLATE_VIS reference_wrapper;
^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:397:1: error: templates must have C++
      linkage
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:399:1: error: templates must have C++
      linkage
template <class>
^~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:402:1: error: templates must have C++
      linkage
template <class _Tp>
^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:405:1: error: templates must have C++
      linkage
template <class _Tp, bool>
^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:408:1: error: templates must have C++
      linkage
template <bool _Bp, class _If, class _Then>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:411:33: error: explicit specialization of
      non-template struct 'conditional'
    struct _LIBCPP_TEMPLATE_VIS conditional<false, _If, _Then> {typedef _Then type;};
                                ^          ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:410:1: error: templates must have C++
      linkage
template <class _If, class _Then>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:417:1: error: templates must have C++
      linkage
template <bool, class _Tp> struct _LIBCPP_TEMPLATE_VIS __lazy_enable_if {};
^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:418:50: error: explicit specialization of
      non-template struct '__lazy_enable_if'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS __lazy_enable_if<true, _Tp> {typedef typename _Tp::type type;};
                                                 ^               ~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:418:1: error: templates must have C++
      linkage
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS __lazy_enable_if<true, _Tp> {typedef typename _Tp::type type;};
^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:420:1: error: templates must have C++
      linkage
template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:421:50: error: explicit specialization of
      non-template struct 'enable_if'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS enable_if<true, _Tp> {typedef _Tp type;};
                                                 ^        ~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:421:1: error: templates must have C++
      linkage
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS enable_if<true, _Tp> {typedef _Tp type;};
^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:430:1: error: templates must have C++
      linkage
template <class _Tp>
^~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/davisa/opt/pyne/src/transmuters.cpp:2:
In file included from /Users/davisa/opt/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:500:1: error: templates must have C++
      linkage
template <class _Tp, _Tp __v>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davisa/opt/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {```

**Comment by scopatz** [comment] 2017-10-05 21:06
So what makes me suspicious is that `__nullptr:35:5: error: templates must have C++ linkage` is a GCC error, not a clang one. I think there is something wrong where it is looking up GCC headers even though you are saying to use clang.  

Can you post the first part of the build please, where CMake selects the compiler?

**Comment by makeclean** [comment] 2017-10-10 15:03
```atomic_data.h generated is the same as existing file, skipping.
atomic_data.cpp generated is the same as existing file, skipping.
/usr/local/bin/cmake
CMake command is
cmake .. -DCMAKE_INSTALL_PREFIX=/Users/davisa/.local -DPYTHON_EXECUTABLE=/usr/bin/python

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- Pyne platform defined as: __APPLE__
-- Build type: Release
-- CMAKE_INSTALL_RPATH: /Users/davisa/.local/lib:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
-- CMake Install Prefix: /Users/davisa/.local
-- Dependency Root Dir (DEPS_ROOT_DIR): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
-- Dependency Hints (DEPS_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
-- Dependency Binary Hints (DEPS_BIN_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
-- Dependency Library Hints (DEPS_LIB_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
-- Dependency Include Hints (DEPS_INCLUDE_HINTS): HINTS;/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
--    HDF5 Root: 
--    HDF5 Include directory: /usr/local/Cellar/hdf5/1.10.1/include;/usr/include;/usr/local/opt/szip/include
--    HDF5 Library directories: 
--    HDF5 Libraries: /usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib
--    HDF5 High Level Libraries: /usr/local/lib/libhdf5_hl.dylib
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: getsitepackages() takes no arguments (1 given)
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_SITE_PACKAGES: 
-- NUMPY_VERSION_STRING = 1.11.3
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES: /usr/local/Cellar/gcc/7.1.0/lib/gcc/7/gcc/x86_64-apple-darwin16.5.0/7.1.0/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/usr/lib/usr/local/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES Before Fix: gfortranquadmathm
-- LIBGCC_S_PATH = /usr/lib/libgcc_s.1.dylib.
-- LIBGCC_S = gcc_s.1.
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES: gfortranquadmathmgcc_s.1
-- LIBS: /usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/usr/local/lib/libhdf5_hl.dylib;/usr/lib/libpython2.7.dylib
-- Include paths for /Users/davisa/opt/pyne/src: /usr/local/Cellar/hdf5/1.10.1/include;/usr/include;/usr/local/opt/szip/include;/Library/Python/2.7/site-packages/numpy/core/include;/Users/davisa/opt/pyne/build/pyne;/Users/davisa/opt/pyne/src
-- Include paths for /Users/davisa/opt/pyne/pyne: /usr/local/Cellar/hdf5/1.10.1/include;/usr/include;/usr/local/opt/szip/include;/Library/Python/2.7/site-packages/numpy/core/include;/Users/davisa/opt/pyne/build/pyne;/Users/davisa/opt/pyne/src
-- Modules to Cythonize: ace;bins;data;dtypes;endf;enrichment;extra_types;jsoncpp;material;nucname;particle;pyne_config;rxname;stlcontainers;tally;transmuters;_utils
-- F2PY F90 FLAGS: 
-- Include paths for /Users/davisa/opt/pyne/pyne/xs: /usr/local/Cellar/hdf5/1.10.1/include;/usr/include;/usr/local/opt/szip/include;/Library/Python/2.7/site-packages/numpy/core/include;/Users/davisa/opt/pyne/build/pyne;/Users/davisa/opt/pyne/src
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/davisa/opt/pyne/build```

**Comment by scopatz** [comment] 2017-10-10 16:36
Hmm with #922 - that was merged in last week, we were able to build on mac successfully.  Maybe we can set up a time to have a video chat about this and go through the error.

**Comment by ljacobson64** [comment] 2017-11-03 19:51
I recently built pyne with clang, and while I didn't find this specific problem, I did find that everything segfaults. Same as #867.

**Comment by gbremer** [comment] 2017-11-05 14:11
I've not been able to build pyne as well and have been following this issue to pick up updates. My build is hanging on cram --

```
[ 27%] Linking Fortran executable hsmrg
gfortran: warning: CMakeFiles/hsmrg.dir/ensdf_processing/HSICC/hsmrg.for.o: linker input file unused because linking not done
gfortran: warning: CMakeFiles/hsmrg.dir/ensdf_processing/nsdflib95.f.o: linker input file unused because linking not done
[ 27%] Built target hsmrg
Scanning dependencies of target pyne
[ 28%] Building CXX object src/CMakeFiles/pyne.dir/atomic_data.cpp.o
[ 29%] Building C object `src/CMakeFiles/pyne.dir/cram.c.o

```

I've cleaned and refreshed and fetched and merged, but no luck. In variably, the build hangs on cram.

This was the first time I've ever tried to build pyne, so have never successfully built it. I am building on Mac. When I first attempted to build, I had also just updated the OS and Xcode.

**Comment by ljacobson64** [comment] 2017-11-05 17:27
How long have you let it hang? For me it takes about 2.5 minutes to compile cram. Perhaps it would be best to add an option to disable building it...

**Comment by scopatz** [comment] 2017-11-06 16:48
Hi All, Are you building in parallel (with `-j 4` or similar)?  I find that it cuts down on overall build time a lot. Also, a PR to disable cram would be fine with me, though I think the default should be on.

**Comment by gbremer** [comment] 2017-11-07 00:02
I let the build run, and the build made it past cram. The build ultimately failed with a stack of errors, same errors as @makeclean encountered.

```
^~~~~~~~~~~~~~~~~~~~
/Users/gbremer/projects/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/gbremer/projects/pyne/src/transmuters.cpp:2:
In file included from /Users/gbremer/projects/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:430:1: error: templates must have C++ linkage
template <class _Tp>
^~~~~~~~~~~~~~~~~~~~
/Users/gbremer/projects/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
In file included from /Users/gbremer/projects/pyne/src/transmuters.cpp:2:
In file included from /Users/gbremer/projects/pyne/src/cram.hpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ccomplex:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:244:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:500:1: error: templates must have C++ linkage
template <class _Tp, _Tp __v>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gbremer/projects/pyne/src/transmuters.cpp:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/pyne.dir/transmuters.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pyne.dir/all] Error 2
make: *** [all] Error 2

--------------------

```

**Comment by gbremer** [comment] 2017-11-07 00:03
Attached is my build output from above

[build.txt](https://github.com/pyne/pyne/files/1448178/build.txt)

**Comment by scopatz** [comment] 2017-11-08 01:53
Hey @gbremer @makeclean, can you please try the proposed fix in #937 and let me know if that works on your machines. Thanks!

**Comment by gbremer** [comment] 2017-11-08 12:39
Giving it a run-through now.

**Comment by gbremer** [comment] 2017-11-08 12:51
Dumb / newbie question while this is churning through -- how can I best pass along those compiler parameters to build in parallel, to use option "-j 4"? Is there an environment variable to take advantage of?

**Comment by scopatz** [comment] 2017-11-08 18:06
You can write setup.py install --user -j 4.  And no dumb questions ;). Did that actually fix the issue?

**Comment by FlanFlanagan** [comment] 2017-11-08 18:19
I tested the PR and merged it in which closed this issue. @gbremer if this is still an issue please feel free to reopen the issue.

**Comment by veeshy** [comment] 2017-11-09 04:21
I had this issue too, installing on High Sierra. The PR above worked to get past the cram part, but then I fail soon after with:

/Users/veeshy/projects/pyne/src/dagmc_bridge.cpp:5:10: fatal error: 'DagMC.hpp' file not found
#include <DagMC.hpp>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/pyne.dir/dagmc_bridge.cpp.o] Error 1

**Comment by ljacobson64** [comment] 2017-11-09 04:22
That issue is caused by an incorrect MOAB version. pyne only supports (up to?) moab 4.9.1, nothing later.

**Comment by gbremer** [comment] 2017-11-09 11:49
After (improperly and then properly) getting things updated and merged, the build is moving past the cram step quickly. However, my build is stalling again later on, so I suspect I may also have a local environment issue. I am optimistic the fix works for me, and will try to confirm things as soon as I can.

**Comment by scopatz** [comment] 2017-11-09 23:00
Thanks All!

**Comment by scopatz** [comment] 2017-11-19 18:53
Ok All, I am also seeing breakages on Mac w/ clang that are caused by the following lines in `source_sampling.h`:

```
#ifdef __cplusplus
extern "C" {
#endif
```

It looks like @elliottbiondo added these, but they don't really make sense to me. The functions and classes declared in this header **are** C++, not C.  The number of templates and the access control makes it so that there is no way that these could have C linkage.  I think the extern C here needs to go but I have no good way of testing.  I'll put in a PR, but can someone please test it locally? Thanks!

**Comment by gonuke** [comment] 2020-08-10 22:05
This was resolved in a previous PR

**Closed as completed by gonuke** 2020-08-10 22:05 UTC
Labels: bug, build
