### ISSUE TITLE
Support for docker image for PyNE on docker hub

### ISSUE THREAD

**Issue by ypark234** [pyne/pyne#1194] opened 2019-11-27 16:44 UTC
I was recently advised to build a docker image for my project based on PyNE to enhance testing it on CI.
While looking at pyne docker hub, I realized that there is no docker image with basic PyNE installed for users to fetch and build on.

@bam241 further suggested to automate the process of updating PyNE-prebuilt docker images on docker hub whenever there is an update on PyNE for users.

**Comment by bam241** [comment] 2019-11-27 16:49
Yes I think we should support both `develop` version and last tagged version as available containers for people to use or build on top of.
We could set triggers in the CI to automatically update, the docker image on `develop` merge and new tags (= new release)

**Comment by gonuke** [comment] 2019-11-27 21:01
Maybe automating it should be a different issue.  We can probably go ahead and publish some images right now!

**Comment by gonuke** [comment] 2020-08-10 22:49
I think we now have a full set of docker images on dockerhub, but they need to be updated and/or this should be automated.

**Comment by gonuke** [comment] 2020-08-17 02:50
I think this is a duplicate of #1161

**Closed as completed by gonuke** 2020-08-17 02:50 UTC
Labels: feature, build, duplicate
